### PR TITLE
add maven wrapper

### PR DESCRIPTION
**Pull request by chrira**
According to the gradle wrapper add the maven wrapper.

This enables the use of this repository without the need of installing maven.

### CODE REVIEW

**Comment by sylvain-combe-sonarsource** [comment]
Having Maven available should not be a problem for any Java developer or DevOps engineer, and we don't want to embed or maintain Maven within this project.

**Comment by chrira** [comment]
@sylvain-combe-sonarsource why did you integrate the gradle wrapper then?

**Comment by sylvain-combe-sonarsource** [comment]
Gradle is evolving fast and brings breaking changes in almost every major version; the Gradle Wrapper has established itself as a standard on Gradle projects.
It is not the case with Maven; the Maven wrapper is far less common and therefore not representative.

**Comment by chrira** [comment]
Ok, thanks for the explanation. Would have been helpful for CI/CD automation or Containerized development.
I understand not to put everything into a repo.

**Pull request closed without merging**
